export default {
  SUCCESS: 200,
  CREATED: 201,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,

  SUCCESS_MESSAGE: "Success",
  ERROR_MESSAGE: "Something went wrong",
  NOT_FOUND_MESSAGE: "Not found",
  USER_NOT_FOUND_MESSAGE: "User not found",
  UNAUTHORIZED_MESSAGE: "Unauthorized",
  FORBIDDEN_MESSAGE: "Forbidden",
  EMAIL_EXISTS_MESSAGE: "Email already exists",
  EMAIL_ALREADY_VERIFIED_MESSAGE: "Email already verified",
  INVALID_CODE_MESSAGE: "Invalid code",
  AUTH_REQUIRED_MESSAGE: "Authentication required",
  INVALID_TOKEN_MESSAGE: "Invalid token",
  FILE_NOT_FOUND_MESSAGE: "File not found",
  EMAIL_NOT_VERIFIED_MESSAGE: "Email not verified",
  INVALID_CREDENTIALS_MESSAGE: "Invalid credentials",
  ACCOUNT_NOT_APPROVED_MESSAGE: "Account not approved",

  AUTH_HEADER_NAME: "x-auth-token",
};
